In [1]:
import sklearn
import numpy
import pandas as pd
from sklearn.svm import SVC
from sklearn import svm

In [4]:
f=open(r"C:\Users\abhinav\Desktop\ML\svm_data")

In [5]:
X=[]
Y=[]

In [6]:
for line in f:
    comps=line.strip().split('\t')
    x=[float(comps[0]),float(comps[1])]
    y=float(comps[2])
    X.append(x)
    Y.append(y)

In [7]:
X=numpy.asarray(X)
Y=numpy.asarray(Y)
clf = SVC()
clf.fit(X, Y) 
clf.support_vectors_
clf.support_ 
clf.n_support_

array([40, 41])

In [11]:
clf1 = svm.SVC(kernel='linear',degree=3)
clf1.fit(X, Y)
clf1.n_support_
clf1.support_vectors_

array([[ -1.16101165,   8.39369078],
       [  2.34752767,   4.5295017 ],
       [ 12.11631344,  17.70352844]])

In [13]:
clf1 = svm.SVC(kernel='poly',degree=3)
clf1.fit(X, Y)
clf1.n_support_
clf1.support_vectors_

array([[ -1.16101165,   8.39369078],
       [ 12.11631344,  17.70352844],
       [ 19.96749215,  11.77640679]])

In [18]:
for kernel in ('poly', 'linear','rbf'):
    clf1 = svm.SVC(kernel=kernel,degree=3)
    clf1.fit(X, Y)
clf1.n_support_
clf1.support_vectors_

array([[ -3.56100783,  -3.46769022],
       [  0.15461167,  -3.97509154],
       [ -1.16101165,   8.39369078],
       [ -3.15456936,   4.87585942],
       [  1.4776166 ,  -0.45193135],
       [ -0.55918139,   3.66067198],
       [ -1.2771354 ,  -3.22416291],
       [ -6.93750893,   0.7020688 ],
       [  2.45388968,   2.91046677],
       [  0.0990604 ,   0.30454479],
       [  5.34117303,  -3.19553617],
       [ -3.90321337,   1.77474123],
       [ -4.19302245,   3.52558089],
       [ -0.97077391,  -0.62661754],
       [  1.16718787,  -1.45563869],
       [ -0.70786929,  -1.56567292],
       [  2.34752767,   4.5295017 ],
       [  2.75051075,  -1.54666104],
       [ -2.99369536,  -2.22576937],
       [ -0.44405042,  -2.11766743],
       [  0.75865088,   0.87614647],
       [  4.07654249,  -3.39156092],
       [ -2.45506843,   3.38072582],
       [  4.66628721,  -3.86040583],
       [  1.14488806,   1.51273535],
       [ -2.80558959,   2.81707963],
       [ -0.63717523,   5.45003927],
 